development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
 
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
  
production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: production
  pool: 5
  username: root
  password: Algorithm12
 